branchName: 'issue-${issue.number}'
autoCloseIssue: true
openDraftPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true

branches:
  - label: bug
    prefix: bugfix/
  - label: '*'
    prefix: feature/
