branchName: 'issue-${issue.number}'
autoCloseIssue: true
openDraftPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
defaultBranch: 'develop'

branches:
  - label: bug
    prefix: bugfix/
  - label: '*'
    prefix: feature/
