version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    mode: 755


hooks:
  # 배포 전(구버전 중지)
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: scripts/install_java.sh
      timeout: 300
      runas: root
    - location: scripts/install_nginx.sh
      timeout: 120
      runas: root
    - location: scripts/configure_nginx.sh
      timeout: 120
      runas: root
    - location: scripts/fetch_config.sh
      timeout: 60
      runas: root

  # 파일 복사 후
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 120
    - location: scripts/set_perms.sh
      timeout: 120
      runas: root

  # 새 버전 시작
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root

  # 서비스 정상화 검증 (헬스체크 엔드포인트 호출)
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root

#  AfterInstall:
#    - location: scripts/stop.sh
#      timeout: 60
#  ApplicationStart:
#    - location: scripts/start.sh
#      timeout: 60
#  AfterInstall:
#    - location: scripts/deploy.sh
#      timeout: 300
#      runas: ec2-user
#      env:
#        APPLICATION_YML: "{{ secrets.APPLICATION_YML }}"
