version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/action

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
#  AfterInstall:
#    - location: scripts/deploy.sh
#      timeout: 300
#      runas: ec2-user
#      env:
#        APPLICATION_YML: "{{ secrets.APPLICATION_YML }}"
