package com.longing.longing.mock;

import com.longing.longing.api.post.domain.Post;
import com.longing.longing.api.post.service.port.PostRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;


public class FakePostRepository implements PostRepository {

    private final Long autoGeneratedId = 1L;
    private final List<Post> data = new ArrayList<>();

    @Override
    public Optional<Post> findById(Long id, Long userId) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public Post save(Post post) {
        if (post.getId() == null || post.getId() == 0) {
            Post newPost = Post.builder()
                    .id(autoGeneratedId)
                    .title(post.getTitle())
                    .content(post.getContent())
                    .user(post.getUser())
                    .build();
            data.add(newPost);
            return newPost;
        } else {
            data.removeIf(item -> item.getId().equals(post.getId()));
            data.add(post);
            return post;
        }
    }

    @Override
    public Page<Post> findAll(Long userId, Pageable pageable) {
        return null;
    }

    @Override
    public void deleteById(Long postId) {

    }

    @Override
    public Page<Post> findAllwithLikeCountAndSearch(Long userId, String keyword, Pageable pageable) {
        return null;
    }

    @Override
    public Page<Post> findMyPostsWithLikeCountAndSearch(Long userId, String keyword, Pageable pageable) {
        return null;
    }

    @Override
    public void flush() {

    }
}
