package com.longing.longing.mock;

import com.longing.longing.api.like.domain.PostLike;
import com.longing.longing.api.like.service.port.PostLikeRepository;
import com.longing.longing.api.post.domain.Post;
import com.longing.longing.api.user.domain.User;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakePostLikeRepository implements PostLikeRepository {

    private final Long autoGeneratedId = 1L;
    private final List<PostLike> postLikeList = new ArrayList<>();

    @Override
    public Optional<PostLike> findByPostAndUser(Post post, User user) {
        return postLikeList.stream()
                .filter(like -> like.getPost().getId().equals(post.getId()) && 
                        like.getUser().getId().equals(user.getId()))
                .findAny();
    }

    @Override
    public void save(PostLike postLike) {
        if (postLike.getId() == null || postLike.getId() == 0) {
            PostLike newPostLike = PostLike.builder()
                    .id(autoGeneratedId)
                    .post(postLike.getPost())
                    .user(postLike.getUser())
                    .build();
            postLikeList.add(newPostLike);
        } else {
            postLikeList.removeIf(item -> item.getId().equals(postLike.getId()));
            postLikeList.add(postLike);
        }
    }

//    @Override
//    public Optional<PostLike> findById(long likeId) {
//        return postLikeList.stream().filter(item -> item.getId().equals(likeId)).findAny();
//    }

    @Override
    public void deleteById(long likeId) {

    }
}
