package com.longing.longing.mock;

import com.longing.longing.api.comment.domain.Comment;
import com.longing.longing.api.comment.service.port.CommentRepository;
import com.longing.longing.api.post.domain.Post;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeCommentRepository implements CommentRepository {

    private final Long autoGeneratedId = 1L;
    private final List<Comment> comments = new ArrayList<>();

    @Override
    public Comment save(Comment comment) {
        if (comment.getId() == null || comment.getId() == 0) {
            Comment newComment = Comment.builder()
                    .id(autoGeneratedId)
                    .content(comment.getContent())
                    .user(comment.getUser())
                    .post(comment.getPost())
                    .build();
            comments.add(newComment);
            return newComment;
        } else {
            comments.removeIf(item -> item.getId().equals(comment.getId()));
            comments.add(comment);
            return comment;
        }
    }

    @Override
    public Optional<Comment> findById(Long id) {
        return comments.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public Page<Comment> findByPostId(long postId, Pageable pageable) {
        return null;
    }

    @Override
    public List<Comment> getCommentList(long postId, long lastCommentId, Pageable pageable) {
        return comments;
    }

    @Override
    public void deleteById(long commentId) {
        comments.removeIf(c -> c.getId().equals(commentId));
    }

    @Override
    public Optional<Comment> findByIdAndUserId(long commentId, long id) {
        return comments.stream()
                .filter(c -> c.getId().equals(commentId)
                        && c.getUser() != null
                        && c.getUser().getId().equals(id))
                .findAny();
    }
}
