package com.longing.longing.mock;

import com.longing.longing.api.post.domain.Post;
import com.longing.longing.api.post.service.port.PostRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.ArrayList;

import java.util.List;
import java.util.Optional;


public class FakePostRepository implements PostRepository {

    private final Long autoGeneratedId = 1L;
    private final List<Post> data = new ArrayList<>();

    @Override
    public Optional<Post> findById(Long id, Long userId) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public Post save(Post post) {
        if (post.getId() == null || post.getId() == 0) {
            Post newPost = Post.builder()
                    .id(autoGeneratedId)
                    .title(post.getTitle())
                    .content(post.getContent())
                    .user(post.getUser())
                    .build();
            data.add(newPost);
            return newPost;
        } else {
            data.removeIf(item -> item.getId().equals(post.getId()));
            data.add(post);
            return post;
        }
    }

    @Override
    public Page<Post> findAll(Long userId, Pageable pageable) {
        return null;
    }

    @Override
    public void deleteById(Long postId) {
        data.removeIf(post -> post.getId().equals(postId));
    }

    @Override
    public Page<Post> findAllwithLikeCountAndSearch(Long userId, String keyword, Pageable pageable) {
        return null;
    }

    @Override
    public Page<Post> findMyPostsWithLikeCountAndSearch(Long userId, String keyword, Pageable pageable) {
        return null;
    }

    @Override
    public Optional<Post> findByIdAndUserId(Long id, Long userId) {
        return data.stream()
                .filter(item -> item.getId().equals(id)
                        && item.getUser().getId().equals(userId))
                .findAny();
    }

    @Override
    public void incrementLikeCount(Long postId) {
        Optional<Post> postOptional = data.stream().filter(item -> item.getId().equals(postId)).findAny();
        postOptional.ifPresent(post -> {
            Post updatedPost = Post.builder()
                    .id(post.getId())
                    .title(post.getTitle())
                    .content(post.getContent())
                    .user(post.getUser())
                    .likeCount(post.getLikeCount() + 1)
                    .build();
            data.removeIf(item -> item.getId().equals(postId));
            data.add(updatedPost);
        });
    }

    @Override
    public void decrementLikeCount(Long postId) {
        Optional<Post> postOptional = data.stream().filter(item -> item.getId().equals(postId)).findAny();
        postOptional.ifPresent(post -> {
            int newLikeCount = Math.max(0, post.getLikeCount() - 1);
            Post updatedPost = Post.builder()
                    .id(post.getId())
                    .title(post.getTitle())
                    .content(post.getContent())
                    .user(post.getUser())
                    .likeCount(newLikeCount)
                    .build();
            data.removeIf(item -> item.getId().equals(postId));
            data.add(updatedPost);
        });
    }

    @Override
    public void incrementCommentCount(Long postId) {

    }

    @Override
    public void decrementCommentCount(Long postId) {

    }

    @Override
    public void flush() {

    }
}
