package com.longing.longing.mock;

import com.longing.longing.api.user.Provider;
import com.longing.longing.api.user.domain.User;
import com.longing.longing.api.user.service.port.UserRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public class FakeUserRepository implements UserRepository {

    private final Long autoGeneratedId = 1L;
    private final List<User> data = new ArrayList<>();

    @Override
    public User save(User user) {
        if (user.getId() == null || user.getId() == 0) {
            User newUser = User.builder()
                    .id(autoGeneratedId)
                    .email(user.getEmail())
                    .name(user.getName())
                    .picture(user.getPicture())
                    .role(user.getRole())
                    .providerId(user.getProviderId())
                    .introduction(user.getIntroduction())
                    .nationality(user.getNationality())
                    .provider(user.getProvider())
                    .build();
            data.add(newUser);
            return newUser;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), user.getId()));
            data.add(user);
            return user;
        }
    }

    @Override
    public Optional<User> findById(long id) {
        return Optional.empty();
    }

    @Override
    public Optional<User> findByEmail(String email) {
        return Optional.empty();
    }

    @Override
    public Optional<User> findByProviderId(String providerId) {
        return Optional.empty();
    }

    @Override
    public Optional<User> findByEmailAndProvider(String email, Provider provider) {
        return data.stream().filter(
                item -> item.getEmail().equals(email) && item.getProvider().equals(provider)
        ).findAny();
    }

    @Override
    public void deleteById(long id) {

    }
}
