package com.longing.longing.mock;

import com.longing.longing.api.post.domain.Post;
import com.longing.longing.api.report.ReportReason;
import com.longing.longing.api.report.domain.PostReport;
import com.longing.longing.api.report.service.port.ReportRepository;
import com.longing.longing.api.user.domain.User;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeReportRepository implements ReportRepository {

    private Long autoGeneratedId = 1L;
    private final List<PostReport> postReports = new ArrayList<>();

    @Override
    public PostReport create(Post post, User user, PostReport postReport) {
//        if (postReport.getId() == null || postReport.getId() == 0) {
//            PostReport newPostReport = PostReport.builder()
//                    .id(autoGeneratedId)
//                    .post(post)
//                    .reporter(user)
//                    .reportReason(postReport.getReportReason())
//                    .build();
//            postReports.add(newPostReport);
//            return newPostReport;
//        } else {
//            postReports.removeIf(item -> item.getId().equals(postReport.getId()));
//            postReports.add(postReport);
//            return postReport;
//        }
        if (postReport.getId() == null || postReport.getId() == 0) {
            // 현재 nextId를 부여하고, 다음 호출을 위해 ++
            PostReport newPostReport = PostReport.builder()
                    .id(++autoGeneratedId)
                    .post(post)
                    .reporter(user)
                    .reportReason(postReport.getReportReason())
                    .build();
            postReports.add(newPostReport);
            return newPostReport;
        } else {
            postReports.removeIf(item -> item.getId().equals(postReport.getId()));
            postReports.add(postReport);
            return postReport;
        }
    }

    @Override
    public Optional<PostReport> findOne(User reporter, Post post, ReportReason reportReason) {
        return postReports.stream()
                .filter(c -> c.getReporter() != null
                        && c.getReporter().getId().equals(reporter.getId())
                        && c.getPost().getId().equals(post.getId()))
                .findAny();
    }
}
